import { fetch } from 'undici';
import fs from 'fs';

/**
 * テキストの主要言語を検出する
 * Voiceger API の text_language パラメータ用
 */
export function detectLanguage(text: string): string {
  // 各言語の文字数をカウント
  let japanese = 0;  // ひらがな・カタカナ
  let korean = 0;    // ハングル
  let chinese = 0;   // CJK漢字（日本語のひらがな・カタカナがなければ中国語と判定）
  let other = 0;

  for (const char of text) {
    const code = char.codePointAt(0)!;
    if (
      (code >= 0x3040 && code <= 0x309F) || // ひらがな
      (code >= 0x30A0 && code <= 0x30FF) || // カタカナ
      (code >= 0xFF65 && code <= 0xFF9F)    // 半角カタカナ
    ) {
      japanese++;
    } else if (code >= 0xAC00 && code <= 0xD7AF) { // ハングル音節
      korean++;
    } else if (
      (code >= 0x4E00 && code <= 0x9FFF) || // CJK統合漢字
      (code >= 0x3400 && code <= 0x4DBF)    // CJK統合漢字拡張A
    ) {
      chinese++; // 漢字（日本語/中国語で共通）
    } else if (/[a-zA-Z]/.test(char)) {
      other++;
    }
  }

  // 日本語: ひらがな・カタカナが1文字でもあれば日本語
  if (japanese > 0) return 'Japanese';
  // 韓国語: ハングルが最多
  if (korean > 0 && korean >= chinese && korean >= other) return 'Korean';
  // 中国語: 漢字のみでひらがな・カタカナなし
  if (chinese > 0 && chinese >= other) return 'Chinese';
  // それ以外は英語
  return 'English';
}

export class VoicegerClient {
  private baseUrl: string;

  constructor(baseUrl: string = 'http://127.0.0.1:8000') {
    this.baseUrl = baseUrl;
  }

  async getSpeakers(): Promise<{ id: string; name: string }[]> {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 2000);
    try {
      const res = await fetch(`${this.baseUrl}/speakers`, { signal: controller.signal });
      clearTimeout(timeout);
      if (!res.ok) return [];
      const data = await res.json() as any;
      if (data && Array.isArray(data.speakers)) {
        return data.speakers;
      }
      return [];
    } catch {
      return [];
    }
  }

  async generateAudio(text: string, speakerId?: string): Promise<Buffer | null> {
    try {
      const language = detectLanguage(text);
      const body: any = {
        text: text,
        text_language: language
      };
      if (speakerId) {
        body.speaker_id = speakerId;
      }

      console.log(`🎤 Voiceger Query: ${text} [${language}] (Speaker: ${speakerId || 'default'})`);
      const res = await fetch(`${this.baseUrl}/tts`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body)
      });

      if (!res.ok) {
        const errText = await res.text();
        throw new Error(`Voiceger API Failed: ${res.status} ${res.statusText} - ${errText}`);
      }

      const data = await res.json() as any;
      if (data && data.file_path) {
        console.log(`✅ Audio Generated via Voiceger: ${data.file_path}`);
        // Read the file generated by Voiceger
        if (fs.existsSync(data.file_path)) {
          const buffer = fs.readFileSync(data.file_path);
          return buffer;
        } else {
          console.error(`❌ Voiceger file not found: ${data.file_path}`);
          return null;
        }
      }
      return null;

    } catch (error) {
      console.error("❌ Voiceger Error:", error);
      console.log("💡 Hint: Voiceger API (FastAPI) は起動していますか？");
      return null;
    }
  }
}
